version: '3.4'

x-mysql57: &mysql57
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: true
  command: >
    mysqld
    --log-bin=mysql-bin.log
    --server-id=1
    --binlog-format=row
    --gtid_mode=on
    --enforce-gtid-consistency=on

x-mysql80: &mysql80
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: true
  command: >
    mysqld
    --log-bin=mysql-bin.log
    --server-id=1
    --binlog-format=row
    --gtid_mode=on
    --enforce-gtid-consistency=on
    --binlog_row_metadata=FULL


x-mariadb: &mariadb
  environment:
    MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
  command: >
    --log-bin=master-bin
    --server-id=1
    --default-authentication-plugin=mysql_native_password
    --binlog-format=row
    --binlog_row_metadata=FULL

services:
  percona-5.7:
    <<: *mysql57
    image: percona:5.7
    ports:
      - "3306:3306"

  percona-5.7-ctl:
    <<: *mysql57
    image: percona:5.7
    ports:
      - "3307:3306"

  percona-8.0:
    <<: *mysql80
    image: percona:8.0
    ports:
      - "3309:3306"

  mariadb-10.6:
    <<: *mariadb
    image: mariadb:10.6
    ports:
      - "3308:3306"
    volumes:
      - type: bind
        source: ./.mariadb
        target: /opt/key_file
      - type: bind
        source: ./.mariadb/my.cnf
        target: /etc/mysql/my.cnf
